# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.5.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - mkdir -p ~/.ssh
          - echo $SSH_KEY > ~/.ssh/id_rsa.tmp # note: assumes base64 encoded ssh key without a passphrase
          - base64 -i -d ~/.ssh/id_rsa.tmp > ~/.ssh/id_rsa
          - chmod 600 ~/.ssh/id_rsa
          - base64 ~/.ssh/id_rsa
          - echo -e "Host *\n StrictHostKeyChecking no\n UserKnownHostsFile=/dev/null" > ~/.ssh/config
          - wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-32bit-static.tar.xz
          - tar xpvf ffmpeg-release-32bit-static.tar.xz
          - find ffmpeg-* -name 'ffmpeg' -exec mv {} /bin/ffmpeg \;
          - pip install -r requirements.txt
          - py.test tests
